name: âœ¨Automated Buildâœ¨

on: [push, pull_request]

jobs:
  testJob:
    name: ðŸ§ªTest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        id: testJob
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: ${{ matrix.testMode }}
          checkName: ðŸ“Test Report (${{ matrix.testMode }})
      - uses: actions/upload-artifact@v4
        with:
          name: Test Report (${{ matrix.testMode }})
          path: ${{ steps.testJob.outputs.artifactsPath }}
          
  buildWindows:
    needs: testJob
    name: ðŸ’»Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customParameters: -BuildOnCloud
          targetPlatform: StandaloneWindows64

      # Check for dirty branch
      - name: Check diff if dirty-branch error caused
        if: failure()
        run: |
          git diff --name-only > modified_files.txt
          echo "List of modified files:"
          cat modified_files.txt
          while read -r line; do
            echo "Changes in $line:"
            git diff "$line"
          done < modified_files.txt

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: build-StandaloneWindows64
          path: build/StandaloneWindows64
  buildMacOS:
    needs: testJob
    name: ðŸ’»macOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customParameters: -BuildOnCloud
          targetPlatform: StandaloneOSX

      # Check for dirty branch
      - name: Check diff if dirty-branch error caused
        if: failure()
        run: |
          git diff --name-only > modified_files.txt
          echo "List of modified files:"
          cat modified_files.txt
          while read -r line; do
            echo "Changes in $line:"
            git diff "$line"
          done < modified_files.txt

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: build-StandaloneOSX
          path: build/StandaloneOSX
          
  buildWebGL:
    needs: testJob
    name: ðŸŒWebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customParameters: -BuildOnCloud
          targetPlatform: WebGL

      # Check for dirty branch
      - name: Check diff if dirty-branch error caused
        if: failure()
        run: |
          git diff --name-only > modified_files.txt
          echo "List of modified files:"
          cat modified_files.txt
          while read -r line; do
            echo "Changes in $line:"
            git diff "$line"
          done < modified_files.txt

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: build-WebGL
          path: build/WebGL
          
  deployPages:
    needs: buildWebGL
    name: ðŸš€Deploy(Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-WebGL
          path: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: deploy-pages
          folder: build/WebGL
